name: 'Open Beats'
author: 'Bpazy'
description: 'Open source for your heart'
inputs:
  GITHUB_NAME:
    description: 'Your Github name, used to commit when Github Action running'
    required: false
    default: ''
  GITHUB_EMAIL:
    description: 'Your Github email, used to commit when Github Action running'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: heart
  color: red
